### ISSUE TITLE
No log entry in activity table

### ISSUE THREAD

**Issue by dvigneshwer** [minrk/log_jupyterhub_activity#1]
I was successfully able to run the log_activity script and it created an activity.sqlite db.
(Changed the port ot 8000 in the script for making it work.)

Following commads I followed to see db entry.

```
sqlite3 activity.sqlite
.open activity.sqlite
.tables
select * from activity;
```

All these commands run without any error but no output was seen in the activity table.

How do I verify if the code is working or not ?

**Comment by dvigneshwer** [comment]
@minrk Can you help me with this ?

**Comment by minrk** [comment]
The command should immediately output something like:

    2016-08-04 09:09:11.967128 0/3 active users

and will display similar statements each time it queries the Hub. What are you seeing as output of the script?

> (Changed the port ot 8000 in the script for making it work.)

The port in the script is still correct, unless you are running JupyterHub's internal interfaces with non-default ports. Are you running this script on the same machine as the Hub?

**Comment by dvigneshwer** [comment]
Yes I am running the script in the same machine where the Hub is running. It is also running the cull service.

I changes the port to 443 as I am running the jupyter Hub with self signed certificate in the log_activity code.

I am using the token genrated by `jupyterhub token` and not the one generated by `jupyterhub token [admin_user]`

Its working fine now. Thanks :)
